version: "3"

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: devopsprojectdb
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: gabrielhgcamargo/devopsproject
    environment:
      DB_HOST: database
        - "SPRING_PROFILES_ACTIVE=homol"
    ports:
      - "9090:9090"
volumes:
  db-volume:
