spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:devopsprojectdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update
      ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: org.hibernate.dialect.PostgreSQLDialect
